#!/usr/bin/env python
import os
import sys
from flask.ext.script import Manager
from pyhours import create_app
from config import config_map, default_config

env = os.path.basename(sys.argv[0]).rsplit('-', 1)[1:]
config = config_map[env[0]] if env else default_config

app = create_app(config)

from pyhours.plugins import db
manager = Manager(app)


@manager.command
def create_all():
    db.create_all()


@manager.command
def drop_all():
    db.drop_all()


if __name__ == "__main__":
    manager.run()
